export const PROVIDER_TYPES = [
  {
    id: 'dgsis-gateway',
    label: 'Gateway Próprio (DGSIS)',
    tagline: '55 modelos · Claude 5, Sonnet 5, Opus 5, GPT-5.5',
    icon: 'server',
    endpoint: 'https://gtw.cloud2.dgsis.com.br/v1/chat/completions',
    keyUrl: null,
    authScheme: 'bearer',
    defaultApiKey: 'sk-b4516085bb758c4e-2exizc-1b9ba3cf',
    readyToUse: true,
    models: [
      { id: 'claude-sonnet-5', label: 'Claude Sonnet 5', context: 200000, maxOutput: 16000 },
      { id: 'claude-opus-5', label: 'Claude Opus 5', context: 200000, maxOutput: 32000 },
      { id: 'Fable-5', label: 'Fable 5', context: 200000, maxOutput: 16000 },
      { id: 'claude-opus-4.8', label: 'Claude Opus 4.8', context: 200000, maxOutput: 32000 },
      { id: 'claude-opus-4.7', label: 'Claude Opus 4.7', context: 200000, maxOutput: 32000 },
      { id: 'claude-opus-4.6', label: 'Claude Opus 4.6', context: 200000, maxOutput: 32000 },
      { id: 'claude-sonnet-4.6', label: 'Claude Sonnet 4.6', context: 200000, maxOutput: 16000 },
      { id: 'gpt-5.5', label: 'GPT-5.5', context: 200000, maxOutput: 16000 },
      { id: 'gemini-3.7-flash', label: 'Gemini 3.7 Flash', context: 1000000, maxOutput: 16000 },
      { id: 'gemini-3.6-flash', label: 'Gemini 3.6 Flash', context: 1000000, maxOutput: 16000 },
      { id: '5.6-Sol', label: 'GPT-5.6 Sol', context: 200000, maxOutput: 16000 },
      { id: '5.6-Terra', label: 'GPT-5.6 Terra', context: 200000, maxOutput: 16000 },
      { id: '5.6-Luna', label: 'GPT-5.6 Luna', context: 200000, maxOutput: 16000 },
      { id: 'ag/gemini-3.7-flash-high', label: 'Gemini 3.7 Flash High (ag)', context: 1000000, maxOutput: 16000 },
      { id: 'ag/gemini-3.7-flash-medium', label: 'Gemini 3.7 Flash Medium (ag)', context: 1000000, maxOutput: 16000 },
      { id: 'ag/gemini-3.7-flash-low', label: 'Gemini 3.7 Flash Low (ag)', context: 1000000, maxOutput: 16000 },
      { id: 'ag/gemini-3.6-flash-high', label: 'Gemini 3.6 Flash High (ag)', context: 1000000, maxOutput: 16000 },
      { id: 'ag/gemini-pro-agent', label: 'Gemini Pro Agent (ag)', context: 1000000, maxOutput: 16000 },
      { id: 'ag/claude-sonnet-4-6', label: 'Claude Sonnet 4.6 (ag)', context: 200000, maxOutput: 16000 },
      { id: 'ag/claude-opus-4-6-thinking', label: 'Claude Opus 4.6 Thinking (ag)', context: 200000, maxOutput: 32000 },
      { id: 'ag/gpt-oss-120b-medium', label: 'GPT OSS 120B (ag)', context: 128000, maxOutput: 8000 },
      { id: 'kr/claude-opus-5', label: 'Claude Opus 5 (kr)', context: 200000, maxOutput: 32000 },
      { id: 'kr/claude-sonnet-5', label: 'Claude Sonnet 5 (kr)', context: 200000, maxOutput: 16000 },
      { id: 'kr/claude-haiku-4.5', label: 'Claude Haiku 4.5 (kr)', context: 200000, maxOutput: 8192 },
      { id: 'kr/deepseek-3.2', label: 'DeepSeek 3.2 (kr)', context: 128000, maxOutput: 8000 },
      { id: 'kr/qwen3-coder-next', label: 'Qwen3 Coder Next (kr)', context: 128000, maxOutput: 16000 },
      { id: 'kr/glm-5', label: 'GLM 5 (kr)', context: 128000, maxOutput: 16000 },
      { id: 'kr/MiniMax-M2.5', label: 'MiniMax M2.5 (kr)', context: 128000, maxOutput: 16000 },
      { id: 'kr/gpt-5.6-sol', label: 'GPT-5.6 Sol (kr)', context: 200000, maxOutput: 16000 },
      { id: 'kr/gpt-5.6-sol-thinking', label: 'GPT-5.6 Sol Thinking (kr)', context: 200000, maxOutput: 32000 },
      { id: 'kr/gpt-5.6-sol-agentic', label: 'GPT-5.6 Sol Agentic (kr)', context: 200000, maxOutput: 32000 },
    ],
  },
  {
    id: 'custom-gateway',
    label: 'Meu Gateway Próprio',
    tagline: 'Adicione qualquer gateway de inferência',
    icon: 'chip',
    endpoint: '',
    keyUrl: null,
    isCustomGateway: true,
    authScheme: 'bearer',
    models: [],
  },
  {
    id: 'github-models',
    label: 'GitHub Models',
    tagline: 'Grátis com sua conta GitHub',
    icon: 'github',
    endpoint: 'https://models.github.ai/inference/chat/completions',
    keyUrl: null,
    free: true,
    usesGithubToken: true,
    models: [
      { id: 'openai/gpt-4o', label: 'GPT-4o', context: 128000, maxOutput: 16000, free: true },
      { id: 'openai/gpt-4o-mini', label: 'GPT-4o mini', context: 128000, maxOutput: 16000, free: true },
      { id: 'openai/gpt-4.1', label: 'GPT-4.1', context: 1000000, maxOutput: 32000, free: true },
      { id: 'openai/gpt-4.1-mini', label: 'GPT-4.1 mini', context: 1000000, maxOutput: 32000, free: true },
      { id: 'openai/o1', label: 'o1 reasoning', context: 200000, maxOutput: 100000, free: true },
      { id: 'openai/o1-mini', label: 'o1 mini', context: 128000, maxOutput: 65000, free: true },
      { id: 'meta/Llama-3.3-70B-Instruct', label: 'Llama 3.3 70B', context: 128000, maxOutput: 8000, free: true },
      { id: 'meta/Meta-Llama-3.1-405B-Instruct', label: 'Llama 3.1 405B', context: 128000, maxOutput: 8000, free: true },
      { id: 'mistral-ai/Mistral-Large-2411', label: 'Mistral Large', context: 128000, maxOutput: 8000, free: true },
      { id: 'deepseek/DeepSeek-V3', label: 'DeepSeek V3', context: 128000, maxOutput: 8000, free: true },
      { id: 'deepseek/DeepSeek-R1', label: 'DeepSeek R1', context: 128000, maxOutput: 8000, free: true },
    ],
  },
  {
    id: 'openrouter',
    label: 'OpenRouter',
    tagline: '400+ modelos, muitos grátis',
    icon: 'router',
    endpoint: 'https://openrouter.ai/api/v1/chat/completions',
    keyUrl: 'https://openrouter.ai/keys',
    models: [
      { id: 'meta-llama/llama-3.3-70b-instruct:free', label: 'Llama 3.3 70B', context: 128000, maxOutput: 8000, free: true },
      { id: 'deepseek/deepseek-chat-v3.1:free', label: 'DeepSeek V3.1', context: 128000, maxOutput: 8000, free: true },
      { id: 'deepseek/deepseek-r1:free', label: 'DeepSeek R1', context: 128000, maxOutput: 8000, free: true },
      { id: 'qwen/qwen-2.5-coder-32b-instruct:free', label: 'Qwen 2.5 Coder 32B', context: 128000, maxOutput: 8000, free: true },
      { id: 'google/gemini-2.0-flash-exp:free', label: 'Gemini 2.0 Flash', context: 1000000, maxOutput: 8000, free: true },
      { id: 'nvidia/llama-3.1-nemotron-70b-instruct:free', label: 'Nemotron 70B', context: 128000, maxOutput: 8000, free: true },
      { id: 'anthropic/claude-sonnet-4', label: 'Claude Sonnet 4', context: 200000, maxOutput: 8192 },
      { id: 'anthropic/claude-opus-4', label: 'Claude Opus 4', context: 200000, maxOutput: 32000 },
      { id: 'openai/gpt-4o', label: 'GPT-4o', context: 128000, maxOutput: 16000 },
      { id: 'x-ai/grok-2', label: 'Grok 2', context: 128000, maxOutput: 8000 },
    ],
  },
  {
    id: 'google',
    label: 'Google Gemini',
    tagline: 'Tier grátis generoso',
    icon: 'google',
    endpoint: 'https://generativelanguage.googleapis.com/v1beta',
    keyUrl: 'https://aistudio.google.com/apikey',
    models: [
      { id: 'gemini-2.0-flash-exp', label: 'Gemini 2.0 Flash', context: 1000000, maxOutput: 8000, free: true },
      { id: 'gemini-2.0-flash-thinking-exp', label: 'Gemini 2.0 Flash Thinking', context: 1000000, maxOutput: 8000, free: true },
      { id: 'gemini-1.5-flash', label: 'Gemini 1.5 Flash', context: 1000000, maxOutput: 8000, free: true },
      { id: 'gemini-1.5-flash-8b', label: 'Gemini 1.5 Flash 8B', context: 1000000, maxOutput: 8000, free: true },
      { id: 'gemini-1.5-pro', label: 'Gemini 1.5 Pro', context: 2000000, maxOutput: 8000, free: true },
      { id: 'gemini-exp-1206', label: 'Gemini Exp 1206', context: 2000000, maxOutput: 8000, free: true },
    ],
  },
  {
    id: 'groq',
    label: 'Groq',
    tagline: 'Ultra rápido, grátis',
    icon: 'bolt',
    endpoint: 'https://api.groq.com/openai/v1/chat/completions',
    keyUrl: 'https://console.groq.com/keys',
    models: [
      { id: 'llama-3.3-70b-versatile', label: 'Llama 3.3 70B', context: 128000, maxOutput: 8000, free: true },
      { id: 'llama-3.1-8b-instant', label: 'Llama 3.1 8B', context: 128000, maxOutput: 8000, free: true },
      { id: 'llama-3.2-90b-vision-preview', label: 'Llama 3.2 90B Vision', context: 128000, maxOutput: 8000, free: true },
      { id: 'mixtral-8x7b-32768', label: 'Mixtral 8x7B', context: 32000, maxOutput: 8000, free: true },
      { id: 'gemma2-9b-it', label: 'Gemma 2 9B', context: 8000, maxOutput: 8000, free: true },
      { id: 'deepseek-r1-distill-llama-70b', label: 'DeepSeek R1 Distill 70B', context: 128000, maxOutput: 8000, free: true },
      { id: 'qwen-2.5-coder-32b', label: 'Qwen 2.5 Coder 32B', context: 128000, maxOutput: 8000, free: true },
    ],
  },
  {
    id: 'cerebras',
    label: 'Cerebras',
    tagline: 'Inferência ultra rápida',
    icon: 'chip',
    endpoint: 'https://api.cerebras.ai/v1/chat/completions',
    keyUrl: 'https://cloud.cerebras.ai',
    models: [
      { id: 'llama3.1-8b', label: 'Llama 3.1 8B', context: 128000, maxOutput: 8000, free: true },
      { id: 'llama-3.3-70b', label: 'Llama 3.3 70B', context: 128000, maxOutput: 8000, free: true },
      { id: 'llama-4-scout-17b-16e-instruct', label: 'Llama 4 Scout', context: 128000, maxOutput: 8000, free: true },
    ],
  },
  {
    id: 'together',
    label: 'Together AI',
    tagline: 'Tier grátis com modelos abertos',
    icon: 'together',
    endpoint: 'https://api.together.xyz/v1/chat/completions',
    keyUrl: 'https://api.together.xyz/settings/api-keys',
    models: [
      { id: 'meta-llama/Llama-3.3-70B-Instruct-Turbo-Free', label: 'Llama 3.3 70B Turbo', context: 128000, maxOutput: 8000, free: true },
      { id: 'meta-llama/Llama-Vision-Free', label: 'Llama Vision', context: 128000, maxOutput: 8000, free: true },
      { id: 'deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free', label: 'DeepSeek R1 Distill 70B', context: 128000, maxOutput: 8000, free: true },
    ],
  },
  {
    id: 'xai',
    label: 'xAI (Grok)',
    tagline: 'Modelos da xAI',
    icon: 'x',
    endpoint: 'https://api.x.ai/v1/chat/completions',
    keyUrl: 'https://console.x.ai',
    models: [
      { id: 'grok-2-latest', label: 'Grok 2', context: 128000, maxOutput: 8000, inPer1M: 2, outPer1M: 10 },
      { id: 'grok-2-1212', label: 'Grok 2 (12/12)', context: 128000, maxOutput: 8000, inPer1M: 2, outPer1M: 10 },
      { id: 'grok-beta', label: 'Grok beta', context: 128000, maxOutput: 8000, inPer1M: 5, outPer1M: 15 },
    ],
  },
  {
    id: 'fireworks',
    label: 'Fireworks AI',
    tagline: 'Modelos rápidos e baratos',
    icon: 'fire',
    endpoint: 'https://api.fireworks.ai/inference/v1/chat/completions',
    keyUrl: 'https://fireworks.ai/api-keys',
    models: [
      { id: 'accounts/fireworks/models/llama-v3p3-70b-instruct', label: 'Llama 3.3 70B', context: 128000, maxOutput: 8000 },
      { id: 'accounts/fireworks/models/deepseek-v3', label: 'DeepSeek V3', context: 128000, maxOutput: 8000 },
      { id: 'accounts/fireworks/models/deepseek-r1', label: 'DeepSeek R1', context: 128000, maxOutput: 8000 },
      { id: 'accounts/fireworks/models/qwen2p5-coder-32b-instruct', label: 'Qwen 2.5 Coder 32B', context: 128000, maxOutput: 8000 },
    ],
  },
  {
    id: 'perplexity',
    label: 'Perplexity',
    tagline: 'Com busca na web',
    icon: 'search',
    endpoint: 'https://api.perplexity.ai/chat/completions',
    keyUrl: 'https://www.perplexity.ai/settings/api',
    models: [
      { id: 'llama-3.1-sonar-small-128k-online', label: 'Sonar Small (com web)', context: 128000, maxOutput: 8000 },
      { id: 'llama-3.1-sonar-large-128k-online', label: 'Sonar Large (com web)', context: 128000, maxOutput: 8000 },
      { id: 'sonar-pro', label: 'Sonar Pro', context: 200000, maxOutput: 8000 },
    ],
  },
  {
    id: 'sambanova',
    label: 'SambaNova',
    tagline: 'Alto throughput',
    icon: 'chip',
    endpoint: 'https://api.sambanova.ai/v1/chat/completions',
    keyUrl: 'https://cloud.sambanova.ai/apis',
    models: [
      { id: 'Meta-Llama-3.3-70B-Instruct', label: 'Llama 3.3 70B', context: 128000, maxOutput: 8000, free: true },
      { id: 'DeepSeek-R1-Distill-Llama-70B', label: 'DeepSeek R1 Distill 70B', context: 32000, maxOutput: 8000, free: true },
      { id: 'Qwen2.5-Coder-32B-Instruct', label: 'Qwen 2.5 Coder 32B', context: 8000, maxOutput: 8000, free: true },
    ],
  },
  {
    id: 'novita',
    label: 'Novita AI',
    tagline: 'Modelos abertos, tier grátis',
    icon: 'star',
    endpoint: 'https://api.novita.ai/v3/openai/chat/completions',
    keyUrl: 'https://novita.ai/settings/key-management',
    models: [
      { id: 'meta-llama/llama-3.3-70b-instruct', label: 'Llama 3.3 70B', context: 128000, maxOutput: 8000, free: true },
      { id: 'deepseek/deepseek-r1', label: 'DeepSeek R1', context: 128000, maxOutput: 8000 },
      { id: 'qwen/qwen-2.5-coder-32b-instruct', label: 'Qwen 2.5 Coder', context: 32000, maxOutput: 8000 },
    ],
  },
  {
    id: 'nebius',
    label: 'Nebius AI Studio',
    tagline: 'Preços agressivos',
    icon: 'star',
    endpoint: 'https://api.studio.nebius.com/v1/chat/completions',
    keyUrl: 'https://studio.nebius.com',
    models: [
      { id: 'meta-llama/Llama-3.3-70B-Instruct', label: 'Llama 3.3 70B', context: 128000, maxOutput: 8000 },
      { id: 'Qwen/Qwen2.5-Coder-32B-Instruct', label: 'Qwen 2.5 Coder 32B', context: 128000, maxOutput: 8000 },
      { id: 'deepseek-ai/DeepSeek-V3', label: 'DeepSeek V3', context: 128000, maxOutput: 8000 },
    ],
  },
  {
    id: 'huggingface',
    label: 'Hugging Face',
    tagline: 'Router HF, grátis',
    icon: 'hf',
    endpoint: 'https://router.huggingface.co/v1/chat/completions',
    keyUrl: 'https://huggingface.co/settings/tokens',
    models: [
      { id: 'meta-llama/Llama-3.3-70B-Instruct', label: 'Llama 3.3 70B', context: 128000, maxOutput: 8000, free: true },
      { id: 'Qwen/Qwen2.5-Coder-32B-Instruct', label: 'Qwen 2.5 Coder 32B', context: 128000, maxOutput: 8000, free: true },
      { id: 'deepseek-ai/DeepSeek-V3', label: 'DeepSeek V3', context: 128000, maxOutput: 8000, free: true },
    ],
  },
  {
    id: 'cohere',
    label: 'Cohere',
    tagline: 'Command R+ e novos',
    icon: 'cohere',
    endpoint: 'https://api.cohere.ai/compatibility/v1/chat/completions',
    keyUrl: 'https://dashboard.cohere.com/api-keys',
    models: [
      { id: 'command-r-plus-08-2024', label: 'Command R+', context: 128000, maxOutput: 4000 },
      { id: 'command-r-08-2024', label: 'Command R', context: 128000, maxOutput: 4000 },
    ],
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    tagline: 'Direto da DeepSeek, barato',
    icon: 'whale',
    endpoint: 'https://api.deepseek.com/v1/chat/completions',
    keyUrl: 'https://platform.deepseek.com/api_keys',
    models: [
      { id: 'deepseek-chat', label: 'DeepSeek Chat', context: 64000, maxOutput: 8000, inPer1M: 0.27, outPer1M: 1.1 },
      { id: 'deepseek-reasoner', label: 'DeepSeek Reasoner', context: 64000, maxOutput: 8000, inPer1M: 0.55, outPer1M: 2.19 },
    ],
  },
  {
    id: 'mistral',
    label: 'Mistral AI',
    tagline: 'Tem tier grátis',
    icon: 'mistral',
    endpoint: 'https://api.mistral.ai/v1/chat/completions',
    keyUrl: 'https://console.mistral.ai/api-keys',
    models: [
      { id: 'mistral-small-latest', label: 'Mistral Small', context: 128000, maxOutput: 8000, free: true },
      { id: 'open-mistral-nemo', label: 'Mistral Nemo', context: 128000, maxOutput: 8000, free: true },
      { id: 'mistral-large-latest', label: 'Mistral Large', context: 128000, maxOutput: 8000 },
      { id: 'codestral-latest', label: 'Codestral', context: 32000, maxOutput: 8000 },
    ],
  },
  {
    id: 'anthropic',
    label: 'Anthropic (Claude)',
    tagline: 'Direto da Anthropic',
    icon: 'anthropic',
    endpoint: 'https://api.anthropic.com/v1/messages',
    keyUrl: 'https://console.anthropic.com/settings/keys',
    models: [
      { id: 'claude-opus-4-5', label: 'Claude Opus 4.5', context: 200000, maxOutput: 32000, inPer1M: 15, outPer1M: 75 },
      { id: 'claude-sonnet-4-5', label: 'Claude Sonnet 4.5', context: 200000, maxOutput: 8192, inPer1M: 3, outPer1M: 15 },
      { id: 'claude-haiku-4-5', label: 'Claude Haiku 4.5', context: 200000, maxOutput: 8192, inPer1M: 1, outPer1M: 5 },
    ],
  },
  {
    id: 'claude-code',
    label: 'Claude Code (via Anthropic)',
    tagline: 'Preset de coding com Claude',
    icon: 'anthropic',
    endpoint: 'https://api.anthropic.com/v1/messages',
    keyUrl: 'https://console.anthropic.com/settings/keys',
    variantOf: 'anthropic',
    models: [
      { id: 'claude-sonnet-4-5', label: 'Sonnet 4.5 (coding)', context: 200000, maxOutput: 8192, inPer1M: 3, outPer1M: 15 },
      { id: 'claude-opus-4-5', label: 'Opus 4.5 (coding avançado)', context: 200000, maxOutput: 32000, inPer1M: 15, outPer1M: 75 },
    ],
  },
  {
    id: 'openai',
    label: 'OpenAI',
    tagline: 'Direto da OpenAI',
    icon: 'openai',
    endpoint: 'https://api.openai.com/v1/chat/completions',
    keyUrl: 'https://platform.openai.com/api-keys',
    models: [
      { id: 'gpt-4o', label: 'GPT-4o', context: 128000, maxOutput: 16000, inPer1M: 2.5, outPer1M: 10 },
      { id: 'gpt-4o-mini', label: 'GPT-4o mini', context: 128000, maxOutput: 16000, inPer1M: 0.15, outPer1M: 0.6 },
      { id: 'gpt-4.1', label: 'GPT-4.1', context: 1000000, maxOutput: 32000, inPer1M: 2, outPer1M: 8 },
      { id: 'o1', label: 'o1 reasoning', context: 200000, maxOutput: 100000, inPer1M: 15, outPer1M: 60 },
      { id: 'o1-mini', label: 'o1 mini', context: 128000, maxOutput: 65000, inPer1M: 3, outPer1M: 12 },
    ],
  },
  {
    id: 'ollama',
    label: 'Ollama (local)',
    tagline: '100% grátis, offline',
    icon: 'server',
    endpoint: 'http://localhost:11434/v1/chat/completions',
    noAuth: true,
    free: true,
    models: [
      { id: 'llama3.2', label: 'Llama 3.2', context: 128000, maxOutput: 4000, free: true },
      { id: 'llama3.3', label: 'Llama 3.3', context: 128000, maxOutput: 4000, free: true },
      { id: 'qwen2.5-coder', label: 'Qwen 2.5 Coder', context: 32000, maxOutput: 4000, free: true },
      { id: 'deepseek-r1', label: 'DeepSeek R1', context: 128000, maxOutput: 4000, free: true },
      { id: 'codellama', label: 'CodeLlama', context: 16000, maxOutput: 4000, free: true },
    ],
  },
  {
    id: 'lmstudio',
    label: 'LM Studio (local)',
    tagline: '100% grátis, offline',
    icon: 'server',
    endpoint: 'http://localhost:1234/v1/chat/completions',
    noAuth: true,
    free: true,
    models: [
      { id: 'local-model', label: 'Modelo local (renomeie)', context: 32000, maxOutput: 4000, free: true },
    ],
  },
  {
    id: 'custom',
    label: 'Custom (OpenAI-compat)',
    tagline: 'Endpoint próprio',
    icon: 'gear',
    endpoint: '',
    keyUrl: null,
    models: [],
  },
];

export function getProviderType(id) {
  return PROVIDER_TYPES.find(p => p.id === id);
}

export function freeProviderTypes() {
  return PROVIDER_TYPES.filter(p => p.free || p.models?.some(m => m.free));
}
